export const COMPONENT_SIZE_RULES = [
  ["1", "Door", "Frame", "Horz", "Top", "Std Width"],
  ["2", "Door", "Frame", "Horz", "Bottom", "Std Width"],
  ["3", "Door", "Frame", "Hinge", "Side", "Std Height"],
  ["4", "Door", "Frame", "Lock Tube", "Side", "Std Lock Tube Height"],
  ["5", "Gate", "Frame", "Horz", "Top", "Std Frame Width"],
  ["6", "Gate", "Frame", "Horz", "Bottom", "Std Frame Width"],
  ["7", "Gate", "Frame", "Hinge", "Side", "Std Height"],
  ["8", "Gate", "Frame", "Lock Tube", "Side", "Std Gate Lock Tube Height"],
  ["9", "1 Frame", "Frame", "Horz", "Top", "Std Frame Width"],
  ["10", "1 Frame", "Frame", "Vert", "Side", "Std Height"],
  ["11", "2 Frame", "Frame", "Horz", "Top", "Std Frame Width"],
  ["12", "2 Frame", "Frame", "Horz", "Bottom", "Std 2 Frame Width"],
  ["13", "2 Frame", "Frame", "Vert", "Side", "Std Height"],
  ["14", "2 Frame", "Frame", "Vert", "Center", "Std Center Height"],
  ["15", "1 Sidelite", "Frame", "Horz", "Top", "Std Frame Width"],
  ["16", "1 Sidelite", "Frame", "Horz", "Bottom", "Std Sidelite Width"],
  ["17", "1 Sidelite", "Frame", "Vert", "Side", "Std Height"],
  ["18", "1 Sidelite", "Frame", "Vert", "Center", "Std Center Height"],
  ["19", "2 Sidelite", "Frame", "Horz", "Top", "Std 2 Sidelite Top Frame Width"],
  ["20", "2 Sidelite", "Frame", "Horz", "Bottom", "Std 2 Sidelite Width"],
  ["21", "2 Sidelite", "Frame", "Horz", "Center", "Std 2 Sidelite Center Width"],
  ["22", "2 Sidelite", "Frame", "Vert", "Side", "Std Height"],
  ["23", "2 Sidelite", "Frame", "Vert", "Center", "Std Center Height"],
  ["24", "Door", "Internal", "Vert", "Top", "Std Top Picket"],
  ["25", "Door", "Internal", "Vert", "Bottom", "Std Bottom Picket"],
  ["26", "Door", "Internal", "Horz", "Top", "Std Width"],
  ["27", "Door", "Internal", "Horz", "Bottom", "Std Width"],
  ["28", "Door", "Internal", "Horz", "Center", "Std Internal Center Width"],
  ["29", "Door", "Opening", "Z-Bar", "Bottom", "Expander"],
  ["30", "Door", "Opening", "Z-Bar", "Side", "Jambs"],
  ["31", "Door", "Opening", "Z-Bar", "Top", "Header"],
  ["32", "Door", "Final", "Glass", "Top", "Top Glass"],
  ["33", "Door", "Final", "Glass", "Bottom", "Bottom Glass"],
  ["34", "Door", "Final", "Glass", "Center", "Center Glass"],
  ["35", "Door", "Final", "Glass", "Full", "Bottom Glass"],
  ["36", "2 Frame", "Internal", "Vert", "Full", "Std Full Height"],
  ["37", "Gate", "Internal", "Vert", "Full", "Std Full Height"],
  ["38", "Gate", "Internal", "Horz", "Center", "Std Internal Center Width"],
  ["39", "2 Frame", "Internal", "Horz", "Center", "Std 2 Frame Width"],
  ["40", "1 Sidelite", "Internal", "Horz", "Center", "Std Sidelite Width"],
  ["41", "1 Sidelite", "Internal", "Vert", "Top", "Std Sidelite Top Picket"],
  ["42", "1 Sidelite", "Internal", "Vert", "Bottom", "Std Sidelite Bottom Picket"],
  ["43", "2 Sidelite", "Internal", "Horz", "Center", "Std 2 Sidelite Width"],
  ["44", "2 Sidelite", "Internal", "Vert", "Top", "Std Sidelite Top Picket"],
  ["45", "2 Sidelite", "Internal", "Vert", "Bottom", "Std Sidelite Bottom Picket"],
  ["46", "Door", "Internal", "Vert", "Center", "Std Center Picket"],
  ["47", "1 Sidelite", "Internal", "Vert", "Center", "Std Center Picket"],
  ["48", "2 Sidelite", "Internal", "Vert", "Center", "Std Center Picket"],
  ["49", "2 Frame", "Opening", "Legs", "Top", "Legs"],
  ["50", "2 Frame", "Opening", "Legs", "Side", "Legs"],
  ["51", "Door", "Final", "Screen", "Top", "Top Screen"],
  ["52", "Door", "Final", "Screen", "Bottom", "Bottom Screen"],
  ["53", "Door", "Final", "Screen", "Center", "Center Screen"],
  ["54", "Door", "Final", "Screen", "Full", "Bottom Screen"],
  ["55", "Door", "Opening", "Z-Bar", "Center", "Jambs"],
  ["56", "Door", "Internal", "Vert-I", "Top", "Std Top Picket - Inside"],
  ["57", "Door", "Internal", "Vert-M", "Top", "Std Top Picket - Middle"],
  ["58", "Door", "Internal", "Vert-O", "Top", "Std Top Picket - Outside"],
  ["59", "Door", "Internal", "Vert-Sun", "Top", "Std Top Picket - Sunrise"],
  ["60", "Door", "Internal", "Vert-Crwn", "Top", "Std Top Picket - Crowned"],
  ["61", "Door", "Internal", "Vert-I", "Top", "Std Top Picket - Inside"],
  ["62", "Door", "Internal", "Vert-M", "Top", "Std Top Picket - Middle"],
  ["63", "Door", "Internal", "Vert-O", "Top", "Std Top Picket - Outside"],
  ["64", "Door", "Internal", "Vert-SmFrz", "Bottom", "Std Bottom Picket - SmFrz"],
  ["65", "Door", "Internal", "Vert-SmFrz", "Top", "Std Top Picket - SmFrz"],
  ["66", "Door", "Internal", "Vert-203O", "Top", "Std Top Picket - 203O"],
  ["67", "Door", "Internal", "Vert-203I", "Top", "Std Top Picket - 203I"],
  ["68", "Door", "Internal", "Vert-203O", "Bottom", "Std Bottom Picket - 203O"],
  ["69", "Door", "Internal", "Vert-203I", "Bottom", "Std Bottom Picket - 203I"],
  ["70", "Door", "Internal", "Horz-203", "Top", "Std Width - 203"],
  ["71", "Door", "Internal", "Horz-203", "Bottom", "Std Width - 203"],
  ["72", "Door", "Internal", "Vert-StFrz", "Bottom", "Std Bottom Picket - StFrz"],
  ["73", "Door", "Internal", "Vert-StFrz", "Top", "Std Top Picket - StFrz"]
];
