export const REFERENCE_CODES = [
  ["1", "Category", "Glass", "Glass"],
  ["3", "Category", "Vert", "Vert piece  ( | | | ) - Normal"],
  ["4", "Category", "Horz", "Horz. piece  ( ---- )"],
  ["5", "Category", "Other", "Other"],
  ["6", "Group", "Frame", "Frame/Internal Component"],
  ["7", "Group", "Design", "Design Component"],
  ["8", "Group", "Final", "Final Component"],
  ["9", "Section", "Top", "Top"],
  ["10", "Section", "Bottom", "Bottom"],
  ["11", "Section", "Center", "Center"],
  ["12", "Door Type", "French", "French Door Set"],
  ["13", "*Key", "Category", "Category"],
  ["14", "*Key", "Group", "Group"],
  ["15", "*Key", "Section", "Section"],
  ["16", "*Key", "Door Type", "Door Type"],
  ["17", "*Key", "Phone", "Phone Types"],
  ["18", "Door Type", "Patio", "Patio Door Set"],
  ["20", "Door Type", "Single", "Single Door"],
  ["51", "*Key", "Color", "Door Color"],
  ["52", "Color", "Bronze", "Bronze"],
  ["53", "Color", "White", "White"],
  ["54", "Color", "Black", "Black"],
  ["55", "Color", "SandStone", "Sandstone"],
  ["56", "*Key", "U/M", "Unit of Measure"],
  ["57", "U/M", "Each", "Each"],
  ["59", "*Key", "Lock", "Lock Types"],
  ["60", "Lock", "Four Way", "Four Way"],
  ["61", "Lock", "Yale", "Yale"],
  ["62", "*Key", "Hinge", "Hinge Side"],
  ["63", "Hinge", "Left", "Left"],
  ["64", "Hinge", "Right", "Right"],
  ["66", "*Key", "Operator", "Operator"],
  ["67", "Operator", "Right", "Right"],
  ["68", "Operator", "Left", "Left"],
  ["69", "Lock", "Slim Line", "Slim Line"],
  ["74", "Category", "Hinge", "Hinge Tube"],
  ["75", "Category", "Lock Tube", "Lock Tube"],
  ["76", "Section", "Side", "Left/Right Side"],
  ["78", "Group", "Opening", "Opening Component"],
  ["79", "Color", "Almond", "Almond"],
  ["80", "Color", "Walnut", "Walnut"],
  ["81", "Color", "Copper", "Copper Vein"],
  ["82", "Color", "Gray", "Gray"],
  ["83", "Lock", "Deluxe", "Deluxe Slim Line"],
  ["84", "*Key", "Glass", "Glass Type"],
  ["85", "Glass", "One", "Full View"],
  ["86", "Glass", "Two", "Two Piece"],
  ["87", "Glass", "Three", "Three Piece"],
  ["88", "Glass", "None", "None"],
  ["89", "Door Type", "1 Gate", "Single Gate"],
  ["90", "Door Type", "2 Gate", "Double Gate"],
  ["91", "Door Type", "1 SideLite", "Single Door with Sidelite"],
  ["92", "Door Type1", "Window", "Window Guard"],
  ["93", "Section", "Full", "Full Length"],
  ["94", "Door Type", "2 SideLite", "Single Door with matching Sidelites"],
  ["100", "*Key", "Product", "Product Type"],
  ["101", "Product", "Door", "Normal Door"],
  ["102", "Product", "1 Sidelite", "Single Sidelite"],
  ["103", "Product1", "Window", "Window Guard"],
  ["104", "*Key", "Options", "Door Option"],
  ["105", "Options", "Four Way", "Four Way lock options"],
  ["106", "Options", "Yale", "Yale lock options"],
  ["107", "Options", "Slim Line", "Slim Line lock options"],
  ["108", "Options", "Gate", "Gate options"],
  ["109", "Options", "Other", "Other options"],
  ["110", "Product", "Gate", "Gate Door"],
  ["111", "Product", "1 Frame", "Single Gate Frame"],
  ["112", "Lock", "None", "None"],
  ["113", "Product", "2 Frame", "Double Gate Frame"],
  ["114", "Product", "2 Sidelite", "Double Sidelite"],
  ["117", "Category", "Z-Bar", "Z-Bar piece"],
  ["118", "Category", "Legs", "Gate Legs"],
  ["119", "Category", "Screen", "Screen"],
  ["120", "Lock", "Yale 1", "Yale - Deadbolt only"],
  ["121", "Category", "Vert-I", "Vert. piece  ( | | | ) - Defender Inside"],
  ["122", "Category", "Vert-M", "Vert. piece  ( | | | ) - Defender Middle"],
  ["123", "Category", "Vert-O", "Vert. piece  ( | | | ) - Defender Outside"],
  ["124", "Category", "Vert-Sun", "Vert. piece  ( | | | ) - Sunrise"],
  ["125", "Category", "Vert-Crwn", "Vert. piece  ( | | | ) - Crowned"],
  ["126", "Lock", "Bee Line", "Bee Line"],
  ["129", "Product", "Vent Unit", "Ventilating Unit"],
  ["131", "Glass", "Two SS", "Two Piece - Self-Storing"],
  ["132", "Color", "Green", "Hunter Green"],
  ["133", "Color", "Silvervein", "Silvervein"],
  ["135", "Color", "Bronze Ham", "Bronze Hammertone"],
  ["139", "Category", "Vert-SmFrz", "Vert. piece  ( | | | ) - SmFrz"],
  ["140", "Category", "Vert-203I", "Vert. piece  ( | | | ) - 203I"],
  ["141", "Category", "Vert-203O", "Vert. piece  ( | | | ) - 203O"],
  ["142", "Category", "Horz-203", "Horz. piece  ( ---- ) - 203"],
  ["143", "Category", "Vert-StFrz", "Vert. piece  ( | | | ) - StFrz"],
  ["144", "Color", "Pantina", "Pantina"],
  ["145", "Color", "Charcoal G", "Charcoal Gray"],
  ["146", "Color", "Rust Text", "Rust Texture"],
  ["147", "Color", "Silver Ham", "Silver Hammertone"]
];
